# Problems on Functions

1. Recall that the *hyperbolic sine*, denoted by $sinh$, is ${exp(x)−exp(−x)\over 2}$. Write a function `my_sinh(x)`, where the output `y` is the *hyperbolic sine* computed on x. Assume that x is a 1by 1 float.

In [57]:
# Validate your function
# In: my_shinh(0)
# Out: 0

# In: my_shinh(1)
# Out: 1.1752

2. Write a function `checker_board(n)`, where the output $m$ is an $n\times n$ array with the following form:

$$m= \begin{array}{ccccc}
         1 & 0 & 1 & 0 & 1\\
         0 & 1 & 0 & 1 & 0\\
         1 & 0 & 1 & 0 & 1\\
         0 & 1 & 0 & 1 & 0\\
         1 & 0 & 1 & 0 & 1
         \end{array}$$


Note that the upper-left element should always be 1. Assume that $n$ is a strictly positive integer.

In [55]:
import numpy as np
def checker_board(n):
    
    print('Checkerboard Pattern:')
    
    # create a n*n matrix
    x = np.ones((n,n), dtype = int)
    
    # Fill with 1 the alternate rows and columns
    x[1::2, ::2] = 0
    x[::2, 1::2] = 0
    
    # print the pattern
    for i in range(n):
        for j in range(n):
            print(x[i][j], end= " ")
        print()
        

In [56]:
# Validate your results


# In: checker_board(1)
# Out: 1

# In: checker_board(2)
# Out: array([[1,0],
#             [0,1]])

# In: checker_board(3)
# Out: array([[1,0,1],
#             [0,1,0],
#              [1,0,1]])

3. Write a function `ar_triangle(b,h)` where the output is the area of a triangle with base, $b,$ and height, $h.$ Recall that the area of a triangle is one-half the base times the height. Assume that $b$ and $h$ are just 1 by 1 float numbers.

In [ ]:
def ar_triangle(b,h):
    '''
    Area of the triangle 
    usong base b and height h
    '''
    area = 0.5 * b * h
    return area

In [54]:
# Validate

# In: ar_triangle(1,1)
# Out: 0.5

# In: ar_triangle(2,1)
# Out: 1

# In: ar_triangle(12,5)
# Out: 30


4. Write a function `split_matrix(m)`, where $m$ is an array, the output is a list $[m1, m2]$ where $m1$ is the left half of $m,$ and $m2$ is the right half of $m.$ In the case where there is an odd number of columns, the middle column should go to $m1.$ Assume that $m$ has at least two columns.

In [52]:
import math
def split_matrix(m):
    '''
    split the matrix
    '''
    a = m[:,range(math.floor(len(m)/2))]
    b = m[:, range(math.floor(len(m)/2),len(m))]
    return a, b

In [53]:
import numpy as np

m = np.ones((5,5))
a,b = split_matrix(m)
print(f"the split of m is\n a = {a} \n and\n b = {b}")
print(f"The size of a is {np.shape(a)} and the size of b is {np.shape(b)} ")

the split of m is
 a = [[1. 1.]
 [1. 1.]
 [1. 1.]
 [1. 1.]
 [1. 1.]] 
 and
 b = [[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]
The size of a is (5, 2) and the size of b is (5, 3) 


5. Write a function `vol_cylinder(r,h)`, where $r$ and $h$ are the radius and height of a cylinder, respectively, and the output is a list $[s, v]$ where $s$ and $v$ are the surface area and volume of the same cylinder, respectively. Recall that the surface area of a cylinder is $2πr^2+2πrh,$ and the volume is $πr^2h.$    Assume that $r$ and $h$ are 1 by 1 float.

In [58]:
def SaVol_cylinder(r,h):
    '''
    r = radius of the cylinder
    h = height of the cylinder
    Computing surface area $2\pir^2+2\pi rh$
    Computing Volume of the cylinder $\pir^2h$
    '''
    Sa = 2 * np.pi * r * (r + h) 
    Vol = np.pi * r * h
    return Sa, Vol 

In [60]:
SaVol_cylinder(1,5)

(37.69911184307752, 15.707963267948966)

In [61]:
# Validate your results
#In: SaVol_cylinder(1,5)
#Out: [37.6991, 15.7080]

#In: SaVol_cylinder(2,4)
#Out: [62.8319, 37.6991]

6. Write a function `n_odds(x)`, where $x$ is a one-dimensional array of floats and the output is the number of odd numbers in $x.$

In [82]:
def n_odd(x):
    total_odd = sum([x[i] % 2 == 1 for i in range(len(x))])
    return total_odd

In [85]:
x = [1, 2, 3, 4,5, 6, 7]
#[x[i] % 2 == 0 for i in range(len(x))]
n_odd(x)
y = n_odd(np.arange(100))
y

50

In [86]:
# Validate your results

# In: n_odds(np.arange(100))
# Out: 50

# In: n_odds(np.arange(2, 100, 2))
# Out: 0

7. Write a function `twos(m,n)`, where the output is an $m×n$ array of twos. Assume that $m$ and $n$ are strictly positive integers.

In [90]:
def twos(m,n):
    x = np.full((m,n),2)
    return x

In [93]:
y = twos(3,2)
y

array([[2, 2],
       [2, 2],
       [2, 2]])

8. a) Write a `lambda` function that takes in $x$ and $y,$ and output the value of $x - y.$

   b) Write a function `add_string(s1,s2)`, where the output is the concatenation of the strings s1 and s2.

In [105]:
diff = lambda x, y: (x-y)
def add_string(s1,s2):
    s = s1 +' '+ s2
    return s

diff(2,3)

-1

In [99]:
diff(3,2)

1

In [100]:
diff(54, 24)

30

In [106]:
s1 = "Hello"
s2 = "World"
add_string(s1,s2)

'Hello World'

In [107]:
# In: s1 = add_string('Programming', ' ')
# In: s2 = add_string('is', 'fun!')
# In: add_string(s1, s2)
# Out: 'Programming is fun!'

9. Write a function `greeting(name,age)`, where name is a string, age is a float, and the output is a string ‘Hi, my name is XXX and I am XXX years old.’ where XXX are the input name and age, respectively.

In [110]:
def greeting(name, age):
    print(f'Hi, my name is {name} and I am {age} years old')

In [114]:
greeting('sampath', 35)

Hi, my name is sampath and I am 35 years old


10. Let $r1$ and $r2$ be the radius of circles with the same center and let $r2>r1.$ Write a function `donut_area(r1, r2)`, where the output is the area outside of the circle with radius $r1$ and inside the circle with radius $r2.$ Make sure that the function is vectorized. Assume that $r1$ and $r2$ are one-dimensional array of the same size.

In [131]:
def donut_area(r1, r2):
    '''
    Area of the circles
    '''
    ar = [abs(np.pi * (r1[i]**2 - r2[i]**2)) for i in range(len(r1))]
    return ar


In [132]:
donut_area(np.arange(1, 4),np.arange(2, 7, 2))


[9.42477796076938, 37.69911184307752, 84.82300164692441]

11. Write a function `within_tolerance(A,a,tol)`, where the output is an array or list of the indices in $A$ such that $|A−a|<tol.$ Assume that $A$ is a one-dimensional float list or array and that $a$ and $tol$ are 1 by 1 floats.

In [170]:
def within_tolerance(A, a, tol):
    '''
    Write about the function!!
    '''
    tolerance = [A[i] for i in range(len(A)) if abs(A[i]-a)<= 0.5]
    return tolerance


In [171]:
within_tolerance([0,1,2,3], 1.5, 0.75)


[1, 2]

12. Write a function `bounding_array(A,top,bottom)`, where the output is equal to the array A wherever bottom < A < top, the output is equal to bottom wherever A <= bottom, and the output is equal to top wherever A >= top. Assume that A is one-dimensional float array and that top and bottom are 1 by 1 floats.

In [184]:
def bounding_array(A,t,b):
    """    Args:
        A ([type]): [description]
        top ([type]): [description]
        bottom ([type]): [description]
    """
    bdd_array = [A[i] for i in range(len(A)) if b <= A[i] <= t]
    return bdd_array

In [185]:

A = np.arange(-6,6)
top = 3
bottom = -3
bounding_array(A,3,-3)

[-3, -2, -1, 0, 1, 2, 3]