# Probelms on Branching
1.    Write a function `tip_calc(bill, party)`, where bill is the total cost of a meal and party is the number of people in the group. The tip should be calculated as 15% for a party strictly less than six people, 18% for a party strictly less than eight, 20% for a party less than 11, and 25% for a party 11 or more. A couple of test cases are given below.

In [1]:
def tip_calc(bill, party):
    """[summary]
    Calculating tip of the bill
    Args:
        bill ([type]): Int or Float
        party ([type]): Int
    """
    if party < 6:
        tip = bill * 0.15
    elif party < 8:
        tip = bill * 0.18
    elif party < 11:
        tip = bill * 0.20
    else:
        tip = bill * 0.25
    return tip


In [3]:
t = tip_calc(109.29, 3)
t

16.3935

In [4]:
t = tip_calc(109.29,7)
t

19.6722

In [5]:
t = tip_calc(109.29,12)
t

27.3225

2.    Write a function `mult_operation(a,b,operation)`. The input argument, operation, is a string that is either 'plus', 'minus', 'mult', 'div', or 'pow', and the function should compute: a+b, a−b, a∗b, a/b, and ab for the respective values for operation. A couple of test cases are given below.

In [6]:
def multiple_op(a,b,op):
    """[summary]
    Calculating multiple operations
    Args:
        a ([type]): Int or Float
        b ([type]): Int or Float
        op ([type]): String
    """
    if op == 'plus':
        out = a+b
    elif op == 'minus':
        out = a-b
    elif op == 'mult':
        out = a*b
    elif op == 'div':
        out = a/b
    else:
        out = a**b
    return out
    

In [8]:
import numpy as np
x = np.array([1,2,3,4])
y = np.array([2,3,4,5])

oplus = multiple_op(x,y,'plus')
oplus

array([3, 5, 7, 9])

In [9]:
ominus = multiple_op(x,y,'minus')
ominus

array([-1, -1, -1, -1])

In [10]:
opow = multiple_op(x,y,'pow')
opow

array([   1,    8,   81, 1024], dtype=int32)

4.    Consider a triangle with vertices at (0,0), (1,0), and (0,1). Write a function `inside_triangle(x,y)` where the output is the string ‘outside’ if the point (x,y) is outside of the triangle, ‘border’ if the point is exactly on the border of the triangle, and ‘inside’ if the point is on the inside of the triangle.

In [33]:
def isInside(x,y):
    """[summary]
    Locating the position of the point
    Args:
        x ([type]): Int or Float
        y ([type]): Int or Float
    """
    def ar_triangle(a,b,c):
        return 0.5 * abs(a[0]*(b[1]-c[1])+b[0]*(c[1]-a[1])+c[0]*(a[1]-b[1]))
    ar1 = ar_triangle((0,0),(0,1),(x,y))
    ar2 = ar_triangle((0,0),(1,0),(x,y))
    ar3 = ar_triangle((1,0),(0,1),(x,y))
    if ar1 == 0 or ar2 == 0 or ar3 == 0:
        position = 'Boundary'
    elif ar1+ar2+ar3 == 0.5:
        position = "Inside"
    else:
        position = "Outside"
    return position

In [34]:
isInside(0.5,0.5)

'Boundary'

In [35]:
isInside(0.25,0.25)

'Inside'

In [36]:
isInside(5,5)

'Outside'

5.    Write a function `make_size10(x)`, where $x$ is an array and output is the first 10 elements of x if x has more than 10 elements, and output is the array x padded with enough zeros to make it length 10 if x has less than 10 elements.

In [55]:

def make_size10(x):
    """[summary]
    Creating an array from x having
    exactly 10 elements
    Args:
        x ([type]): [array]
    """
    if len(x) < 10:
        y = np.zeros((1,10-len(x)))
        size10 = np.append(x,y)
    else:
        size10 = x[0:10]
    return np.array(size10)

In [53]:
x = np.array([1,2,3,6,8,8,9,1])
#x=np.append(x,0)
make_size10(x)

array([1., 2., 3., 6., 8., 8., 9., 1., 0., 0.])

Learn more about np.append from the [document](https://numpy.org/doc/stable/reference/generated/numpy.append.html).

In [56]:
make_size10(range(1,15))

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [59]:
make_size10((5,5))

array([5., 5., 0., 0., 0., 0., 0., 0., 0., 0.])

6.    Can you write my_make_size10 without using if-statements (i.e., using only logical and array operations)?

7.    Write a function `letter_grader(percent)`, where grade is the string ‘O’ if percent is greater than 80, ‘A’ if percent is greater than 70, ‘B‘ if percent is greater than 60, ‘C’ if percent is greater than 40, and ‘F’ if percent is less than 40. Grades exactly on the division should be included in the higher grade category.

In [66]:
def letter_grader(percent):
    """[summary]
    Converting percent into letter grades
    Args:
        percent ([type]): [Int or Float]
    """
    if percent > 80:
        grade = "O"
    elif percent > 70:
        grade = "A"
    elif percent > 60:
        grade = "B"
    elif percent > 50:
        grade = "C"
    elif percent >= 40:
        grade = "D"
    else:
        grade = "F"
    return grade

In [67]:
letter_grader(84)

'O'

In [68]:
letter_grader(97)

'O'

In [69]:
letter_grader(65)

'B'

8.    Consider a nuclear reactor whose temperature is monitored by three sensors. An alarm should go off if any two of the sensor readings disagree. Write a function `nuke_alarm(s1,s2,s3)` where s1, s2, and s3 are the temperature readings for sensor 1, sensor 2, and sensor 3, respectively. The output should be the string ‘alarm!’ if any two of the temperature readings disagree by strictly more than 10 degrees and ‘normal’ otherwise.

In [73]:
def nuke_alarm(s1,s2,s3):
    """[summary]

    Args:
        s1 ([type]): [description]
        s2 ([type]): [description]
        s3 ([type]): [description]
    """
    if abs(s1-s2) > 10 or abs(s1-s3)> 10 or abs(s2-s3)> 10:
        response = 'alarm!'
    else:
        response = 'normal'
    return response

In [75]:
nuke_alarm(20,5,15)

'alarm!'

In [76]:
nuke_alarm(95,96,80)

'alarm!'

9.    Write a function `n_roots(a,b,c)`, where $a, b,$ and $c$ are the coefficients of the quadratic $Q(x)$, the function should return two values: `n_roots` is number of roots  and `r` is the roots of $Q(x).$ `n_roots` is 2 if Q has two real roots, 1 if Q has one root, −2 if Q has two imaginary roots, and r is an array containing the roots of Q.

In [81]:
def n_roots(a,b,c):
    """[summary]

    Args:
        a ([type]): [description]
        b ([type]): [description]
        c ([type]): [description]
    """
    delta = b**2-4*a*c
    if delta == 0:
        n_roots = 1
        r = - b / (2*a)
    elif delta > 0:
        n_roots = 2
        r = [- (b - np.sqrt(delta))  / (2*a),- (b + np.sqrt(delta))  / (2*a)]
    else:
        n_roots = 2
        r = [complex(-b/ (2*a), -(np.sqrt(-delta)/ (2*a))),complex(-b/ (2*a), (np.sqrt(-delta)/ (2*a)))]
        
    return n_roots, r 

In [82]:
n_roots(1,0,-9)

(2, [3.0, -3.0])

In [83]:
n_roots(2,4,2)

(1, -1.0)

In [84]:
n_roots(3,4,5)

(2,
 [(-0.6666666666666666-1.1055415967851332j),
  (-0.6666666666666666+1.1055415967851332j)])

10. Write a function `split_function(f,g,a,b,x)`, where $f$ and $g$ are handles to functions f(x) and g(x), respectively. The output should be $f(x)$ if $x≤a, g(x)$ if $x≥b,$ and 0 otherwise. You may assume that $b>a.$